# Site settings
title: The Phat Plats
description: >
  The Phat Plats team offical SWEN 444 project blog.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://phat-plats.github.io" # the base hostname & protocol for your site

author:
  fullname: The Phat Plats
  github: phat-plats
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
