# Site settings
title: Team 6 Blog
subtitle: SWEN-440: Software Requirements & Architecture
description: >
  SWEN-440

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://swen-440-team-6.github.io" # the base hostname & protocol for your site

author:
  fullname: SWEN-440-Team-6
  github: swen-440-team-6
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
